In [ ]:
import pandas as pd
import os
import plotly.express as px

 # Análisis de Visualización de Clusters vs Perpetrador / Víctima

    ---

    ## 📌 Descripción General
    Este script carga resultados de clustering para **víctimas** y **perpetradores**, define funciones para generar gráficos 3D interactivos con Plotly y genera tablas con el conteo y el porcentaje de cada estado (Perpetrador / Víctima) por *cluster*.

    - **Imports y rutas**  
      - `pandas`: manejo de DataFrames  
      - `os`: creación de carpetas  
      - `plotly.express`: visualización 3D interactiva  
      - Rutas a CSV de resultados de clustering y variables  

    - **Funciones principales**  
      - `visualize_cluster_perpetrator(df)`  
      - `visualize_cluster_victim(df)`  

    ---

    ## 🔍 Flujo de Trabajo

    1. **Lectura de datos**  
       ```python
       vic_cl_df    = pd.read_csv(path_cl_vic)
       per_cl_df    = pd.read_csv(path_cl_per)
       pred_var_df  = pd.read_csv(path_var)
       target_df    = pd.read_csv(path_target)
       ```

    2. **Definición de funciones**

       ### `visualize_cluster_perpetrator(df)`

       - Crea la carpeta `perpetrador_clustering` si no existe.  
       - Prepara el *DataFrame*:  
         - Convierte `PERPETRADOR` a entero.  
         - Crea la etiqueta `PERP_LABEL` ↔ `{0: "No Perpetrador", 1: "Perpetrador"}`.  
       - Gráfico 3D con `px.scatter_3d`:  
         - Ejes: `umap_1`, `umap_2`, `umap_3`.  
         - Color por `PERP_LABEL` (verde / rojo).  
         - Información en *hover*: número de cluster.  
         - Guarda el HTML en `perpetrador_clustering/umap_3d_perpetrador.html`.  
       - Calcula la tabla de **conteo** y **porcentaje** por `(cluster, PERPETRADOR)`.  
       - Devuelve el *DataFrame* ordenado.  

       ### `visualize_cluster_victim(df)`

       - Crea la carpeta `victim_clustering` si no existe.  
       - Prepara el *DataFrame*:  
         - Convierte `VÍCTIMA` a entero.  
         - Crea la etiqueta `V_LABEL` ↔ `{0: "No Víctima", 1: "Víctima"}`.  
       - Gráfico 3D con `px.scatter_3d`:  
         - Ejes: `umap_1`, `umap_2`, `umap_3`.  
         - Color por `V_LABEL` (verde / rojo).  
         - Información en *hover*: número de cluster.  
         - Guarda el HTML en `victim_clustering/umap_3d_victima.html`.  
       - Calcula la tabla de **conteo** y **porcentaje** por `(cluster, VÍCTIMA)`.  
       - Devuelve el *DataFrame* ordenado.  

    ---

    ## 🏃‍♂️ Ejecución y guardado de resultados
    ```python
    counts_per_df = visualize_cluster_perpetrator(vic_cl_df)
    counts_per_df.to_csv("perpetrador_clustering/cluster_perpetrators.csv", index=False)
    display(counts_per_df)

    counts_vict_df = visualize_cluster_victim(per_cl_df)
    counts_vict_df.to_csv("victim_clustering/cluster_victima.csv", index=False)
    display(counts_vict_df)
    ```

    ---

    ## 📈 Interpretación
    - Cada gráfico 3D muestra cómo se distribuyen víctimas y perpetradores en el espacio UMAP 3D.  
    - Las tablas finales permiten observar, por *cluster*, la proporción de sujetos en cada estado.  
    - Esta nueva información (etiqueta de *cluster*) puede enriquecer un clasificador supervisado, aportando contexto sobre la probabilidad de ser víctima o perpetrador según el *cluster* asignado.  

    ---

    ## 🏆 Resultados Generados
    - **HTML 3D interactivo** para perpetradores: `perpetrador_clustering/umap_3d_perpetrador.html`  
    - **HTML 3D interactivo** para víctimas: `victim_clustering/umap_3d_victima.html`  
    - **CSV** resumen de conteos y porcentajes:  
      - `cluster_perpetrators.csv`  
      - `cluster_victima.csv`

In [2]:
path_cl_vic = r"victim_clustering\comb_56_results.csv"
path_cl_per = r"perpetrador_clustering\comb_130_results.csv"
path_var = r"data\lista_global_vars.csv"
path_target = r"data\target_col.csv"

vic_cl_df = pd.read_csv(path_cl_vic)
per_cl_df = pd.read_csv(path_cl_per)
pred_var_df = pd.read_csv(path_var)
target_df = pd.read_csv(path_target)

In [41]:
pred_var_df["CONVIVEN.5"].value_counts()

CONVIVEN.5
1.0    2545
0.0    1479
Name: count, dtype: int64

In [3]:
print("Dimensión:",target_df.shape)
target_df.head()

Dimensión: (4024, 11)

,VÍCTIMA,PERPETRADOR,VICTIMA_PERPETRADOR,POLIVICTIMIZACION,POLIPERPETRACION,SOLO.VICTIMA,SOLO.PERPETRADOR,NO.VICT_NO.PERP,V.O,P.SUM.TOTAL,V.SUM.TOTAL
0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0
2,1.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,0.0,2.0
3,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0

In [4]:
print("Dimensión:",vic_cl_df.shape)
vic_cl_df.head()

Dimensión: (4024, 4)

      umap_1     umap_2    umap_3  cluster
0  -8.279517   4.240156  2.679671        0
1  10.078565  -6.147625 -6.578492        1
2  23.133938 -13.754403  0.893848        2
3  -8.309052   4.325134  2.839835        0
4  -8.155433   4.561926  3.167857        0

In [5]:
print("Dimensión:",pred_var_df.shape) 
pred_var_df.head()

Dimensión: (4024, 29)

,PAÍS,ETNIA.BN,EDAD,FUGAS.BN,ABUSOSUBS1,ABUSOSUBS2,CONVIVEN.1,CONVIVEN.2,CONVIVEN.3,CONVIVEN.4,...,APOYO.VAR,MORAL.MEAN,MORAL.VAR,PORNO.T,GENERO_BIN_0,GENERO_BIN_1,GENERO_BIN_2,ORIENTSEX.BN_1,ORIENTSEX.BN_2,ORIENTSEX.BN_3
0,1,0.0,16.0,0.0,4,4,1.0,1.0,0.0,0.0,...,0.000000,5.0,0.00,1.0,0,1,0,1,0,0
1,1,0.0,16.0,0.0,3,2,1.0,1.0,0.0,0.0,...,0.530612,2.8,0.56,4.0,1,0,0,1,0,0
2,1,0.0,17.0,0.0,3,3,1.0,1.0,0.0,0.0,...,0.775510,4.2,0.96,3.0,0,1,0,1,0,0
3,1,0.0,16.0,0.0,3,3,1.0,1.0,0.0,0.0,...,0.775510,4.0,0.40,4.0,1,0,0,1,0,0
4,1,0.0,17.0,0.0,3,3,1.0,1.0,0.0,0.0,...,0.530612,4.4,1.44,2.0,0,1,0,1,0,0

In [6]:
df_vic_cl_target = vic_cl_df.join(target_df["PERPETRADOR"])
df_per_cl_target = per_cl_df.join(target_df["VÍCTIMA"])

In [10]:
print("Número de clusteres:",len(df_vic_cl_target["cluster"].value_counts().values))
print("Perpetador si o no:",len(df_vic_cl_target["PERPETRADOR"].value_counts().values))
print("Possibles combinaciones: ",len(df_vic_cl_target["cluster"].value_counts().values)*len(df_vic_cl_target["PERPETRADOR"].value_counts().values))
print("Combinaciones encontradas: ",len(df_vic_cl_target[["cluster","PERPETRADOR"]].value_counts().values))
df_vic_cl_target[["cluster","PERPETRADOR"]].value_counts()

Número de clusteres: 9
Perpetador si o no: 2
Possibles combinaciones:  18
Combinaciones encontradas:  18

cluster  PERPETRADOR
0        0.0            1842
3        0.0             568
         1.0             524
0        1.0             183
1        0.0             149
7        0.0             134
6        0.0             103
2        0.0              90
4        0.0              70
5        0.0              67
1        1.0              57
8        0.0              51
6        1.0              40
2        1.0              35
7        1.0              34
5        1.0              34
4        1.0              24
8        1.0              19
Name: count, dtype: int64

In [26]:
def visualize_cluster_perpetrator(df):
    """
    Genera un gráfico 3D interactivo de UMAP coloreado por PERPETRADOR,
    guarda el HTML en 'perpetrador_clustering' y devuelve un DataFrame
    con el conteo de pares (cluster, PERPETRADOR) y su porcentaje dentro de cada cluster.
    """
    # Crear carpeta si no existe
    output_dir = "perpetrador_clustering"
    os.makedirs(output_dir, exist_ok=True)
    
    # Preparar DataFrame
    df = df.copy()
    df['PERPETRADOR'] = df['PERPETRADOR'].astype(int)
    df['PERP_LABEL'] = df['PERPETRADOR'].map({
        0: 'No Perpetrador',
        1: 'Perpetrador'
    })
    
    # Crear gráfico 3D
    fig = px.scatter_3d(
        df,
        x='umap_1', y='umap_2', z='umap_3',
        color='PERP_LABEL',
        color_discrete_sequence=['green', 'red'],
        labels={'PERP_LABEL': 'Estado'},
        title='UMAP 3D – Perpetradores vs No Perpetradores',
        hover_data=['cluster']
    )
    fig.update_traces(marker=dict(size=4))
    fig.update_layout(
        legend=dict(title='Perpetrador', itemsizing='constant'),
        margin=dict(l=0, r=0, b=0, t=30)
    )

    # Mostrar en notebook
    fig.show()

    # Guardar HTML
    html_path = os.path.join(output_dir, "umap_3d_perpetrador.html")
    fig.write_html(html_path, include_plotlyjs='cdn')

    # Calcular conteos y porcentaje
    counts = (
        df[['cluster', 'PERPETRADOR']]
        .value_counts()
        .reset_index(name='count')
    )
    # Calcular total por cluster
    total_cluster = counts.groupby('cluster')['count'].transform('sum')
    counts['percentage'] = (counts['count'] / total_cluster * 100).round(2)
    
    # Ordenar y resetear índice
    counts = counts.sort_values(['cluster', 'PERPETRADOR']).reset_index(drop=True)
    
    return counts

def visualize_cluster_victim(df):
    """
    Genera un gráfico 3D interactivo de UMAP coloreado por VÍCTIMA,
    guarda el HTML en 'victim_clustering' y devuelve un DataFrame
    con el conteo de pares (cluster, VÍCTIMA) y su porcentaje dentro de cada cluster.
    """
    # Crear carpeta si no existe
    output_dir = "victim_clustering"
    os.makedirs(output_dir, exist_ok=True)
    
    # Preparar DataFrame
    df = df.copy()
    df['VÍCTIMA'] = df['VÍCTIMA'].astype(int)
    df['V_LABEL'] = df['VÍCTIMA'].map({
        0: 'No víctima',
        1: 'Víctima'
    })
    
    # Crear gráfico 3D
    fig = px.scatter_3d(
        df,
        x='umap_1', y='umap_2', z='umap_3',
        color='V_LABEL',
        color_discrete_sequence=['green', 'red'],
        labels={'V_LABEL': 'Estado'},
        title='UMAP 3D – Víctima vs No Víctima',
        hover_data=['cluster']
    )
    fig.update_traces(marker=dict(size=4))
    fig.update_layout(
        legend=dict(title='Víctima', itemsizing='constant'),
        margin=dict(l=0, r=0, b=0, t=30)
    )

    # Mostrar en notebook
    fig.show()

    # Guardar HTML
    html_path = os.path.join(output_dir, "umap_3d_victima.html")
    fig.write_html(html_path, include_plotlyjs='cdn')

    # Calcular conteos y porcentaje
    counts = (
        df[['cluster', 'VÍCTIMA']]
        .value_counts()
        .reset_index(name='count')
    )
    # Calcular total por cluster
    total_cluster = counts.groupby('cluster')['count'].transform('sum')
    counts['percentage'] = (counts['count'] / total_cluster * 100).round(2)
    
    # Ordenar y resetear índice
    counts = counts.sort_values(['cluster', 'VÍCTIMA']).reset_index(drop=True)
    
    return counts

In [21]:
# Clústeres hechos en función del típo de víctima.
# Vemos rápidamente que tipo de víctima tiene más probabilidad de ser perpetrador en base a su frecuencia dentro del clúster. 
# Vemos también que esta nueva variable (cluster) nos puede ayudar mucho a enriquecer al clasificador de perpretador. 
# Es decir, sabiendo el tipo de víctima junto con las variables globales seguramente la performance del clasificador aumentará.
# Asumción: Sabemos que tipo de víctima es -> Saber si es perpretador o no.   
counts_per_df = visualize_cluster_perpetrator(df_vic_cl_target)
counts_per_df.to_csv(r"perpetrador_clustering\cluster_perpetrators.csv",index=False)
display(counts_per_df)

    cluster  PERPETRADOR  count  percentage
0         0            0   1842       90.96
1         0            1    183        9.04
2         1            0    149       72.33
3         1            1     57       27.67
4         2            0     90       72.00
5         2            1     35       28.00
6         3            0    568       52.01
7         3            1    524       47.99
8         4            0     70       74.47
9         4            1     24       25.53
10        5            0     67       66.34
11        5            1     34       33.66
12        6            0    103       72.03
13        6            1     40       27.97
14        7            0    134       79.76
15        7            1     34       20.24
16        8            0     51       72.86
17        8            1     19       27.14

In [27]:
# clusters hechos en función del tipo de perpretador.
# Vemos rápidamente que tipo de perpretador tiene más probabilidad de ser víctima en base a su frecuencia. 
# Vemos también que esta nueva variable nos puede ayudar mucho a enriquecer al clasificador de víctima. 
# Es decir, sabiendo el tipo de perpetrador que es junto con las variables globales seguramente se puede saber si el sujeto es víctima o no. 
# Asumción: Sabemos que tipo  de perpetrador es -> Saber si es víctima o no.   
counts_vict_df = visualize_cluster_victim(df_per_cl_target)
counts_vict_df.to_csv(r"victim_clustering\cluster_victima.csv",index=False)
display(counts_vict_df)

   cluster  VÍCTIMA  count  percentage
0        0        0   1854       59.40
1        0        1   1267       40.60
2        1        0     43       28.86
3        1        1    106       71.14
4        2        0     29       10.90
5        2        1    237       89.10
6        3        0     33       11.11
7        3        1    264       88.89
8        4        0     52       27.23
9        4        1    139       72.77